trigger:
  - main

pool:
  name: "Default"

stages:
  - stage: NugetValidation
    jobs:
      - job: NugetValidation
        displayName: Nuget Validation
        pool: "Default"
        steps:
          - checkout: self
            displayName: Checkout NugetTestRepo
          - task: NuGetAuthenticate@1
            inputs:
              feedUrl: "https://pkgs.dev.azure.com/mseng/AzureDevOps/_packaging/AzureDevOps_PublicPackages/nuget/registry/"
          - task: PowerShell@2
            inputs:
              targetType: "inline"
              script: "Get-Content $(Build.SourcesDirectory)/nuget.config"
          - task: PowerShell@2
            inputs:
              targetType: "inline"
              script: "Get-Content $(Build.SourcesDirectory)/NugetNoclear/nuget.config"
          - task: PowerShell@2
            inputs:
              targetType: "inline"
              script: "Get-Content $(Build.SourcesDirectory)/NugetNonAA/nuget.config"
          - task: DotNetCoreCLI@2
            displayName: Build BasicNonCompliant
            inputs:
              command: build
              feedsToUse: config
              nugetConfigPath: "$(Build.SourcesDirectory)/nuget.config"
              projects: "$(Build.SourcesDirectory)/BasicNonCompliant/test.csproj"
              arguments: >
                --no-restore
                --configfile $(Build.SourcesDirectory)/nuget.config
                --verbosity detailed

          - task: DotNetCoreCLI@2
            displayName: Build BasicNonCompliant
            inputs:
              command: build
              feedsToUse: config
              projects: "$(Build.SourcesDirectory)/NugetNoclear/subfolder/test.csproj"
              nugetConfigPath: "$(Build.SourcesDirectory)/NugetNoclear/nuget.config"
              arguments: >
                --no-restore
                --configfile $(Build.SourcesDirectory)/NugetNoclear/nuget.config
                --verbosity detailed

          - task: DotNetCoreCLI@2
            displayName: Build BasicNonCompliant
            inputs:
              command: build
              feedsToUse: config
              projects: "$(Build.SourcesDirectory)/NugetNonAA/subfolder/test.csproj"
              nugetConfigPath: "$(Build.SourcesDirectory)/NugetNonAA/nuget.config"
              arguments: >
                --no-restore
                --configfile $(Build.SourcesDirectory)/NugetNonAA/nuget.config
                --verbosity detailed
